import cv2
import numpy as np
import matplotlib.pyplot as plt
ima = cv2.imread(r"Imagenes\cell.jpg")
cell=cv2.cvtColor(ima,cv2.COLOR_BGR2RGB)
plt.imshow(cell)
plt.show()
imgB=cell[:,:,2]
plt.imshow(imgB, cmap='gray')
plt.axis('on')
plt.show()
u,bin=cv2.threshold(imgB,100,255,cv2.THRESH_BINARY)
plt.imshow(bin, cmap='gray')
plt.axis('on')
plt.show()
kernel = np.ones((3,3),np.uint8)
# ima2 = cv2.dilate(bin,kernel,iterations = 2)
# ima2 = cv2.erode(ima2,kernel,iterations = 2)
imaOp2=cv2.morphologyEx(bin, cv2.MORPH_OPEN, kernel, iterations = 2)
plt.imshow(imaOp2, cmap='gray')
plt.axis('on')
plt.show()
fin=cv2.morphologyEx(imaOp2, cv2.MORPH_CLOSE, kernel, iterations = 5)
plt.imshow(fin, cmap='gray')
plt.axis('on')
plt.show()
elem,mask=cv2.connectedComponents(fin)
print (elem)
plt.imshow(mask)
plt.show()
Tam=np.zeros(elem)
for i in range(elem):
    Tam[i]=np.sum(mask==i)
print ('Tamanhos de todos los elementos ', Tam)
